# Generated by Django 5.0 on 2023-12-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroosValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_groos', models.FloatField()),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('frete', models.FloatField()),
                ('box_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LiquidValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquid_value', models.FloatField()),
            ],
        ),
    ]
