# Generated by Django 5.0 on 2023-12-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidvalue',
            name='month',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
    ]
