# Generated by Django 5.0 on 2023-12-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisil', '0002_liquidvalue_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisilValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency', models.FloatField()),
                ('boleto', models.FloatField()),
                ('invest', models.FloatField()),
                ('lucro', models.FloatField()),
            ],
        ),
    ]
