# Generated by Django 5.0 on 2023-12-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisil', '0003_gisilvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisilvalues',
            name='imposto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
