# Generated by Django 5.0 on 2024-01-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisil', '0004_gisilvalues_imposto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifinitionsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.FloatField()),
                ('frete_cust', models.FloatField()),
            ],
        ),
    ]
