# Generated by Django 5.0 on 2024-01-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisil', '0005_difinitionsvalues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DifinitionsValues',
            new_name='DefinitionsValues',
        ),
    ]
