# Generated by Django 5.0 on 2024-01-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisil', '0006_rename_difinitionsvalues_definitionsvalues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definitionsvalues',
            old_name='box',
            new_name='box_cust',
        ),
    ]
